name: Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  doxygen:
    name: Generate and Deploy Doxygen Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Generate Documentation for predajnik
        run: |
          cd kodovi/predajnik/
          doxygen Doxyfile
          cd ../../

      - name: Generate Documentation for kontroler
        run: |
          cd kodovi/kontroler_robota/
          doxygen Doxyfile
          cd ../../

      - name: Combine documentation into one directory
        run: |
          mkdir -p combined-docs/predajnik
          mkdir -p combined-docs/kontroler
          cp -r kodovi/predajnik/docs/html/* combined-docs/predajnik/
          cp -r kodovi/kontroler_robota/docs/html/* combined-docs/kontroler/

      - name: Deploy Combined Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: combined-docs
